### ISSUE TITLE
nil unique index in Ohm 3.0.0  triggers lua error under Redis unstable

### ISSUE THREAD

**Issue by slowernet** [soveran/ohm#210] opened 2016-04-14 15:11 UTC
The switch from msgpack to json seems to be triggering a lua error when an attribute with a `unique` index is `nil`.

```
class Car < Ohm::Model
	attribute :make; unique :make
end
```

`Car.create` works under 2.3.0, but with 3.0.0:

```
irb(main):004:0> Car.create
RuntimeError: ERR Error running script (call to f_679b3bc0d854f081164a6bfbf06fa027bb625b4b): @user_script:82: @user_script: 82: Lua redis() command arguments must be strings or integers 
	from /ohm-test/vendor/ruby/2.3.0/gems/redic-1.5.0/lib/redic.rb:43:in `call!'
	from /ohm-test/vendor/ruby/2.3.0/gems/ohm-3.0.0/lib/ohm.rb:1399:in `script'
	from /ohm-test/vendor/ruby/2.3.0/gems/ohm-3.0.0/lib/ohm.rb:1350:in `save'
	from /ohm-test/vendor/ruby/2.3.0/gems/ohm-3.0.0/lib/ohm.rb:1098:in `create'
```

**Comment by soveran** [comment] 2016-04-14 16:19
@slowernet I'm not able to reproduce it, is that all the code you used? Just in case, can you tell me the Redis version you are running?

**Comment by slowernet** [comment] 2016-04-14 16:56
I'm sorry, I should have mentioned I am running Redis unstable. I also do not see the problem on 3.0.7.

[redis-info.txt](https://github.com/soveran/ohm/files/219578/redis-info.txt)

**Comment by soveran** [comment] 2016-04-14 18:01
@slowernet Excellent, thanks! I pushed the fix already, you can grab the new gem (version 3.0.1).

**Closed by soveran** 2016-04-14 18:01 UTC

**Comment by slowernet** [comment] 2016-04-14 18:20
Thank you, @soveran.
